"""initial schema"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # noqa: F401  (UtcDateTime columns below render as app.db.UtcDateTime)


revision: str = 'e951365fb128'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('block', sa.String(length=80), nullable=False),
    sa.Column('emergency_number', sa.String(length=32), nullable=False),
    sa.Column('confirm_window_sec', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_district'), 'regions', ['district'], unique=False)
    op.create_index(op.f('ix_regions_state'), 'regions', ['state'], unique=False)
    op.create_table('backup_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_contacts_region_id'), 'backup_contacts', ['region_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_region_id'), 'users', ['region_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_code', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('caller_phone', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('track', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_caller_phone'), 'call_sessions', ['caller_phone'], unique=False)
    op.create_index(op.f('ix_call_sessions_ref_code'), 'call_sessions', ['ref_code'], unique=True)
    op.create_index(op.f('ix_call_sessions_region_id'), 'call_sessions', ['region_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_started_at'), 'call_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_call_sessions_status'), 'call_sessions', ['status'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=8), nullable=False),
    sa.Column('ambiguous', sa.Boolean(), nullable=False),
    sa.Column('repeats', sa.Integer(), nullable=False),
    sa.Column('asked_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('answered_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'question_id')
    )
    op.create_index(op.f('ix_answers_call_id'), 'answers', ['call_id'], unique=False)
    op.create_table('dispatch_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ambulance_confirmed_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('backup_confirmed_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('exhausted_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_cases_call_id'), 'dispatch_cases', ['call_id'], unique=True)
    op.create_index(op.f('ix_dispatch_cases_status'), 'dispatch_cases', ['status'], unique=False)
    op.create_table('incident_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_log_call_id'), 'incident_log', ['call_id'], unique=False)
    op.create_table('status_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('message_key', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_messages_call_id'), 'status_messages', ['call_id'], unique=False)
    op.create_table('triage_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('flagged', sa.JSON(), nullable=False),
    sa.Column('unclear_count', sa.Integer(), nullable=False),
    sa.Column('guidance', sa.JSON(), nullable=False),
    sa.Column('decided_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('fail_safe', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_results_call_id'), 'triage_results', ['call_id'], unique=True)
    op.create_index(op.f('ix_triage_results_tier'), 'triage_results', ['tier'], unique=False)
    op.create_table('dispatch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_kind', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('due_at', app.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dispatch_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_events_case_id'), 'dispatch_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_dispatch_events_created_at'), 'dispatch_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_dispatch_events_due_at'), 'dispatch_events', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_events_due_at'), table_name='dispatch_events')
    op.drop_index(op.f('ix_dispatch_events_created_at'), table_name='dispatch_events')
    op.drop_index(op.f('ix_dispatch_events_case_id'), table_name='dispatch_events')
    op.drop_table('dispatch_events')
    op.drop_index(op.f('ix_triage_results_tier'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_call_id'), table_name='triage_results')
    op.drop_table('triage_results')
    op.drop_index(op.f('ix_status_messages_call_id'), table_name='status_messages')
    op.drop_table('status_messages')
    op.drop_index(op.f('ix_incident_log_call_id'), table_name='incident_log')
    op.drop_table('incident_log')
    op.drop_index(op.f('ix_dispatch_cases_status'), table_name='dispatch_cases')
    op.drop_index(op.f('ix_dispatch_cases_call_id'), table_name='dispatch_cases')
    op.drop_table('dispatch_cases')
    op.drop_index(op.f('ix_answers_call_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_call_sessions_status'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_started_at'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_region_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_ref_code'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_caller_phone'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_region_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_backup_contacts_region_id'), table_name='backup_contacts')
    op.drop_table('backup_contacts')
    op.drop_index(op.f('ix_regions_state'), table_name='regions')
    op.drop_index(op.f('ix_regions_district'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###